remote_theme: mmistakes/minimal-mistakes@4.24.0

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# site settings
locale: "en-US"
title: "Learning By Sharing"
title_separator: "-"
subtitle: "All about awesome things!"
name: &name "Leon Liu" # &name is a YAML anchor which can be *referenced later
description: &description "Blogs for programming, music, traveling, all the fun stuffs."
author: "Leon Liu(CS2K)"
name: "Leon Liu"
url: "https://leonliu.github.io"
repository: "leonliu/leonliu.github.io"
teaser: "/assets/img/teaser.jpeg" # path of fallback teaser image
logo: "/assets/img/logo.png"

# masthead_title: # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : false # true, false (default)

words_per_minute: 200

atom_feed:
  path: # blank (default) uses feed.xml

search: true # true, false (default)
search_full_content: true # true, false (default)
search_provider: google # lunr (default), algolia
google:
  search_engine_id: "410557ea02ba243fd"

# comment
comments:
  provider: "disqus"
  disqus:
    shortname: "leonliu-github-io"

# Site Author
author:
  name: "Leon Liu"
  avatar: "/assets/img/avatar.png"
  bio: "Programmer, music lover and mountaineer."
  location: "Auckland, NZ"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:liu.l.leon@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://leonliu.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/l14967"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/leonliu"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true 

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed