title: "LEARNING BY SHARING"
description: "Miscellaneous article written before and now"
author: "Leon Liu(CS2K)"
url: https://leonliu.github.io
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes@4.24.0
